on: [push, pull_request]

name: CI

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [16.x, 18.x]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: oven-sh/setup-bun@v1
        if: ${{ matrix.os != 'windows-latest' }}
        with:
          bun-version: latest

      - uses: pnpm/action-setup@v2

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test:ci

      - name: Test Bun
        if: ${{ matrix.os != 'windows-latest' }}
        run: pnpm test:bun
